#set working directory to location of unzipped ".txt" file
consumption <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
library("dplyr", lib.loc="~/R/win-library/3.2")
consumption=mutate(consumption, DateTime=paste(Date, Time))
consumption$DateTime=strptime(consumption$DateTime, "%d/%m/%Y %H:%M:%S")
consumption$Date=as.Date(consumption$Date, "%d/%m/%Y")
plotdays=subset(consumption, Date=="2007-02-01" | Date=="2007-02-02")
png(filename = "plot3.png")
with(plotdays, {
  plot(DateTime, Sub_metering_1, xlab="", ylab = "Energy sub metering", type = "l")
  lines(DateTime, Sub_metering_2, col="red")
  lines(DateTime, Sub_metering_3, col="blue")
  })
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), pch = "_")
dev.off()
